// resources/js/components/Footer.svelte
<script lang="ts">
</script>

<footer
    class="relative p-5 overflow-hidden text-gray-700 bg-gray-200 border-t border-gray-500 footer dark:bg-gray-800 dark:text-white"
>
    <div
        class="flex flex-row justify-between w-full text-center"
    >
        <div class="w-full md:w-1/2" style="z-index: 1;">
            <div class="w-3/4 mx-auto">
                <a
                    href="https://github.com/abo3adel"
                    target="_blank"
                    class="mt-2 mr-2 !text-gray-700 !border-gray-700 btn hover:bg-gray-600"
                >
                    <i class="fab fa-github" />
                </a>
                <a
                    href="https://codepen.io/abo3adel"
                    target="_blank"
                    class="mt-2 mr-2 !text-red-700 !border-red-700 btn hover:bg-red-600"
                >
                    <i class="fab fa-codepen" />
                </a>
                <a
                    href="https://www.linkedin.com/in/ahmed-adel-30a932119/"
                    target="_blank"
                    class="mt-2 mr-2 !text-orange-700 !border-orange-700 btn hover:bg-orange-600"
                >
                    <i class="fab fa-linkedin-in" />
                </a>
                <a
                    href="https://fb.com/a7md200"
                    target="_blank"
                    class="mt-2 mr-2 btn"
                >
                    <i class="fab fa-facebook-f" />
                </a>
                <a
                    href="https://wa.me/201143647417"
                    target="_blank"
                    class="mt-2 mr-2 !text-green-700 !border-green-700 btn hover:bg-green-600"
                >
                    <i class="fab fa-whatsapp" />
                </a>
            </div>
        </div>
        <div class="w-full capitalize md:w-1/2" style="z-index: 1;">
            made with
            <span class="text-lg text-red-700 dark:text-red-500">&hearts;</span>
            by
            <span style="font-variant: small-caps"> Ahmed Adel </span>
            2018 -
            <span>
                {new Date().getFullYear()}
            </span>
        </div>
    </div>
    <div
        class="absolute border-4 border-t-8 rounded-full -bottom-40 -left-20 w-80 h-80 border-opacity-30"
    />
    <div
        class="absolute border-4 border-t-8 rounded-full -top-40 -right-0 w-80 h-80 border-opacity-30"
    />
</footer>

// components/footer.vue
<template>
    <footer
        class="footer text-light p-5 border-top border-secondary"
        :class="$route.path === '/' ? 'bg-transparent' : 'bg-dark'"
    >
        <div class="container">
            <div class="row text-center py-4">
                <div class="mx-auto w-75">
                    <a
                        href="https://github.com/abo3adel"
                        target="_blank"
                        class="btn btn-outline-primary btn-brand transition mr-2 mt-2"
                    >
                        <i class="fab fa-github"></i>
                    </a>
                    <a
                        href="https://codepen.io/abo3adel"
                        target="_blank"
                        class="btn btn-outline-danger btn-brand transition mr-2 mt-2"
                    >
                        <i class="fab fa-codepen"></i>
                    </a>
                    <a
                        href="https://www.linkedin.com/in/ahmed-adel-30a932119/"
                        target="_blank"
                        class="btn btn-outline-info btn-brand transition mr-2 mt-2"
                    >
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a
                        href="https://fb.com/a7md200"
                        target="_blank"
                        class="btn btn-outline-primary btn-brand transition mr-2 mt-2"
                    >
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a
                        href="https://wa.me/201143647417"
                        target="_blank"
                        class="btn btn-outline-success btn-brand transition mr-2 mt-2"
                    >
                        <i class="fab fa-whatsapp"></i>
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-12 text-center">
                    made with <span class="text-danger">&hearts;</span> by
                    ninjaCoder 2019 - {{ new Date().getFullYear() }}
                </div>
            </div>
        </div>
    </footer>
</template>
<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
@Component
export default class Footer extends Vue {}
</script>
<style lang="scss">
footer {
    div {
        z-index: 9;
    }
    background: rgba($color: var(--dark), $alpha: 0.1);
}
</style>
